ProductHunt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import account.urls, product.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(account.urls)),
    path('product/', include(product.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

product/urls.py
from django.urls import path
from product import views

app_name = 'product'

urlpatterns = [
    path('', views.allProducts, name='home'),
    path('create/', views.create, name='create'),
    path('<int:product_id>/', views.display, name='display'),
    path('upvote/<int:product_id>/', views.upvote, name='upvote'),
    path('upvote_wo/<int:product_id>/', views.upvote_wo, name='upvote_wo')

]

account/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    title = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    body = models.TextField()
    url = models.TextField()
    image = models.ImageField(upload_to='product/images/')
    icon = models.ImageField(upload_to='product/images/')
    votes_total = models.IntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'],password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('product:home')
        else:
            return render(request, 'account/login.html',{'error':'username or password is incorrect.'})
    else:
        return render(request, 'account/login.html')

def signup(request):
    if request.method == "POST":
        if request.POST['password'] == request.POST['password-re']:
            try:
                user = User.objects.get(username = request.POST['username'])
                return render(request, 'account/signup.html', {'error':'username is already taken'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password'])
                auth.login(request,user)
                return redirect('product:home')
        else:
            return render(request, 'account/signup.html', {'error':'Passwords must match'})
    else:
        return render(request, 'account/signup.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('account:login')

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Product
from django.utils import timezone



def allProducts(request):
    products = Product.objects.all
    return render(request, 'product/home.html', {'products':products})


@login_required(login_url="/account/signup")
def create(request):
    if request.method == "POST":
        if request.POST['title'] and request.POST['body'] and request.POST['url'] and request.FILES['icon'] and request.FILES['image']:
            product = Product()
            product.title = request.POST['title']
            product.body = request.POST['body']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                product.url = request.POST['url']
            else:
                product.url = 'http://' + request.POST['url']
            product.icon = request.FILES['icon']
            product.image = request.FILES['image']
            product.pub_date = timezone.datetime.now()
            product.user = request.user
            product.save()
            return redirect(f'/product/{product.id}')
        else:
            return render(request, 'product/create.html',{'error':'All fields are required.'})
    else:
        return render(request, 'product/create.html')




@login_required(login_url="/account/signup")
def display(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'product/display.html',{'product':product})



@login_required(login_url="/account/signup")
def upvote(request, product_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=product_id)
        product.votes_total += 1
        product.save()
        return redirect(f'/product/{product.id}')


@login_required(login_url="/account/signup")
def upvote_wo(request, product_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=product_id)
        product.votes_total += 1
        product.save()
        return redirect('/product/')

ProductHunt/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <link rel="icon" href="{% static 'images/otp.png' %}" type="image/icon type">
    <title>ProductHunt</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>
  <body>

    {% block header %}
    {% endblock %}


<main role="main">


  {% block jumbotron %}
  {% endblock %}


  {% block content %}
  {% endblock %}




</main>

{% block footer %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

ProductHunt/templates/components/footer.html
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.4/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>

ProductHunt/templates/components/header.html
{% load static %}
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
<a class="navbar-brand" href="#">
  <img src="{% static 'images/load.gif' %}" width="30" height="30" class="d-inline-block align-top" alt="">
  ProductHunt
</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
<div class="navbar-nav ml-auto">
  {% if user.is_authenticated %}
  <a class="nav-item nav-link active" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout</a>
  <form id="logout" method="POST" action="{% url 'account:logout' %}">
       {% csrf_token %}
       <input type="hidden" />
  </form>
  {% else %}
  <a class="nav-item nav-link {% if islogin %} active {% endif %}" href="{% url 'account:login' %}">Login</a>
  <a class="nav-item nav-link {% if not islogin %} active {% endif %}" href="{% url 'account:signup' %}">SignUp</a>
  {% endif %}
</div>
</div>
</nav>
</header>

ProductHunt/templates/components/jumbo.html
<section class="jumbotron text-center">
  <div class="container">
    <h1>ProductHunt ...</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <a href="#" class="btn btn-primary my-2">Main call to action</a>
      <a href="#" class="btn btn-secondary my-2">Secondary action</a>
    </p>
  </div>
</section>

product/templates/product/create.html
{% extends 'base.html' %}

{% block footer %}
{% include 'components/footer.html' %}
{% endblock %}

{% block header %}
{% include 'components/header.html' with islogin=True %}
{% endblock %}

{% block content %}
{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<h1>Create</h1>

<form method="POST" action="{% url 'product:create' %}" enctype="multipart/form-data">
{% csrf_token %}
Title:
<br />
<input type="text" name="title" />
<br />
Body:
<br />
<input type="textbox" name="body" />
<br />
URL:
<br />
<input type="text" name="url" />
<br />
Icon:
<br />
<input type="file" name="icon" />
<br />
Image:
<br />
<input type="file" name="image" />
<br />
<br />
<input class="btn btn-primary" type="submit" value="Add Product" />
</form>

{% endblock %}

product/templates/product/display.html
{% extends 'base.html' %}

{% block footer %}
{% include 'components/footer.html' %}
{% endblock %}

{% block header %}
{% include 'components/header.html' with islogin=True %}
{% endblock %}


{% block content %}

<div class="row">
  <div class="col-2">
    <img src="{{ product.icon.url }}" class="img-fluid" />
  </div>
  <div class="col-10">
    <a href="{{ product.url }}"><h1>{{ product.title }}</h1></a>
  </div>
</div>

<div class="row">
  <div class="col-8">
    <img src="{{ product.image.url }}" class="img-fluid" />
  </div>
  <div class="col-4">
    <a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-primary btn-lg btn-block"><span class="oi oi-caret-top"></span> Upvote {{ product.votes_total }}</button></a>
  </div>
</div>

<div class="row pt-2">
  <div class="col-4">
    <h4><span class="oi oi-magnifying-glass"></span> Hunted by {{ product.hunter.username }}</h4>
  </div>
  <div class="col-4 text-right">
    <h4><span class="oi oi-clock"></span> {{ product.pub_date_pretty }}</h4>
  </div>
</div>

<div class="row">
  <div class="col-8">
    <p>{{ product.body }}</p>
  </div>
</div>

<form id="upvote" method="POST" action="{% url 'product:upvote' product.id %}">
  {% csrf_token%}
  <input type="hidden">
</form>

{% endblock %}

product/templates/product/home.html
{% extends 'base.html' %}

{% block header %}
{% include 'components/header.html' with islogin=True %}
{% endblock %}

{% block jumbotron %}
{% include 'components/jumbo.html' %}
{% endblock %}


{% block content %}
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">

{% for product in products %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{product.image.url}}" alt="Image">
          <div class="card-body">
            <a href="{% url 'product:display' product.id %}"><h3>{{product.title}}</h3></a>
            <p class="card-text">{{product.summary}}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="javascript:{document.getElementById('upvote{{product.id}}').submit()}"><button  type="button" class="btn btn-sm btn-primary">Upvote {{product.votes_total}}</button></a>
                <form id="upvote{{product.id}}" method="POST" action="{% url 'product:upvote_wo' product.id %}">
                   {% csrf_token %}
                   <input type="hidden" />
                </form>
              </div>
              <small class="text-muted">{{product.pub_date_pretty}}</small>
            </div>
          </div>
        </div>
      </div>
{% endfor %}


    </div>


  </div>
</div>
{% endblock %}

{% block footer %}
{% include 'components/footer.html' %}
{% endblock %}